completed all functionality
jamesmaddern/CMP1903M-Assessment-1 pull request #1
Opened 2022-03-24 13:08 UTC by jamesmaddern

2022-03-25 17:24 UTC, domh25 requested changes
-more comments are needed in this project
-more features need to be added to functionality as explained in brief and maybe letter frequency
-report needs more methods
-location of report is unknown when outputting as a txt file

2022-03-25 20:03 UTC, hazzakak commented
- More comments are needed. Particularly in the for loop in the program file.
- 2.6GiB TXT file worked very quickly so big up.
- Through testing, txt files work very well but the program accepts an exe file so could provide a check against whether it's a txt file or not.
- Could do with better named variables (s could be better described etc)
- You have consistent naming conventions tho so yup yup.

2022-03-29 16:52 UTC, Bailey-Ward commented on CMP1903M Assessment 1 Base Code/Input.cs
> +            try
Error handling is implemented which is good, might be worth commenting to point it out as per the brief

2022-03-29 16:52 UTC, Bailey-Ward commented on CMP1903M Assessment 1 Base Code/Program.cs
> +            Analyse analyse = new Analyse();
Good use of objects throughout program

2022-03-29 16:52 UTC, Bailey-Ward commented on CMP1903M Assessment 1 Base Code/Analyse.cs
> +                    }
Would maybe make sense to have the sentence counter in with the other counters? Could add a letter frequency checker too.

2022-03-30 19:18 UTC, merged